//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetActive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervenant
    {
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Telephone { get; set; }
        public int IdClient { get; set; }
        public string NomProjet { get; set; }
        public int CodeProjet { get; set; }
        public string Fonction { get; set; }
        public Nullable<int> DureeIntervention { get; set; }
        public int IdContact { get; set; }
        public string NomClient { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
